---
command: /Users/Bood/mypro/leela-zero/bin/leelaz -d -t 1 -p 1600 --noponder -w /Users/Bood/mypro/leela-zero/bin/af9
tests:
  # Ladder tests
  - name: ladder1.sgf
    sgf: ladder1.sgf
    group: ladder
    move: black
    no_move:
      - P7
  - name: ladder2
    sgf: ladder2.sgf
    group: ladder
    move: black
    no_move:
      - G4
  - name: ladder3
    sgf: ladder3.sgf
    group: ladder
    move: white
    no_move:
      - P11
  - name: ladder4
    sgf: ladder4.sgf
    group: ladder
    move: black
    no_move:
      - P6
  - name: ladder5
    sgf: ladder5.sgf
    group: ladder
    move: white
    no_move:
      - J6
  - name: ladder6
    sgf: ladder6.sgf
    group: ladder
    move: white
    no_move:
      - F14
  - name: ladder7
    sgf: ladder7.sgf
    group: ladder
    move: white
    no_move:
      - G6
  - name: ladder8
    sgf: ladder8.马天放.2018.3.7.sgf
    group: ladder
    number: 41
    move: black
    no_move:
      - G16
  - name: ladder9
    sgf: 误逃征子_20180308.sgf
    group: ladder
    move: black
    no_move:
      - E11
  - name: ladder10
    sgf: 看错征子_20180308.sgf
    group: ladder
    number: 156
    move: white
    max_win_rate: 40
  - name: ladder11
    sgf: 10b-545权重征子bug.sgf
    group: ladder
    number: 56
    move: white
    no_move:
      - K7
  - name: 33point-ladder
    sgf: aq_lz_33point_ladder.sgf
    group: ladder
    number: 15
    move: black
    no_move:
      - Q7
  - name: cut-ladder-misread
    sgf: ladder_misread_by_cut_52_20180308.sgf
    group: ladder
    number: 52
    move: white
    no_move:
      - G3

  # Life & Death tests
  - name: make_life1
    sgf: lifedeath1.sgf
    group: lifedeath
    move: white
    yes_move:
      - M10
  - name: make_life2
    sgf: 娱乐版围棋执黑中盘胜alphaleela_20180308.sgf
    group: lifedeath
    number: 116
    move: white
    yes_move:
      - M19
  - name: make_life3
    sgf: 隐忍黑衣人_alphaleela_20180307.sgf
    group: lifedeath
    number: 217
    move: white
    yes_move:
      - P9
      - Q9
  - name: j_group_live1
    sgf: lifedeath2.sgf
    group: lifedeath
    number: 222
    move: white
    yes_move:
      - S18 # This moves makes life for white

  # Large group sensitive tests
  - name: largegroup_no_liberty_dead
    sgf: zen7-LZaf9.sgf
    group: largegroup
    move: white
    max_win_rate: 10
  - name: largegroup_some_liberty_dead
    sgf: zen7-LZaf9.sgf
    group: largegroup
    number: 256
    move: white
    max_win_rate: 10
  - name: largegroup_atari1
    sgf: largegroup_atari1.sgf
    group: largegroup
    number: 294
    move: white
    yes_move:
      - E1
  - name: largegroup_dead1
    sgf: zen7_LZ.sgf
    group: largegroup
    move: white
    max_win_rate: 40
  - name: largegroup_dead2
    sgf: jinduan(P)_LZ.sgf
    group: largegroup
    move: white
    max_win_rate: 40
  - name: largegroup_dead3
    sgf: zen7_lz_largegroup_20180306.sgf
    group: largegroup
    number: 206
    move: white
    max_win_rate: 40
  - name: largegroup_dead4
    sgf: 娱乐版围棋执黑中盘胜alphaleela_20180308.sgf
    group: largegroup
    number: 196
    move: white
    max_win_rate: 30
  - name: dead_group_misread
    sgf: 11990416-120-Bifron-RoyalZero.sgf
    group: largegroup
    number: 117
    move: black
    max_win_rate: 40

  - name: endgame1
    sgf: endgame1.sgf
    group: endgame
    number: 289
    move: black
    yes_move:
      - S19

  - name: endgame2
    sgf: endgame2.sgf
    group: endgame
    number: 270
    move: white
    no_move:
      - G19

  - name: reduce_liberty_misread
    sgf: 低K官子看错输棋.sgf
    group: endgame
    number: 322
    move: white
    yes_move:
      - H7
      - K8

  # Capture Race tests
  - name: race1
    sgf: MaTianFang_LZ_20180227.sgf
    group: race
    number: 63
    move: black
    yes_move:
      - S11

  - name: race2
    sgf: MaTianFang_LZ_20180227.sgf
    group: race
    number: 65
    move: black
    yes_move:
      - R10
